In [7]:
import pandas as pd

area_dict = {'CA':423967, 'TX':695662, 'NY':141297, 'FL':170312, 'IL':149995} #python dict
area = pd.Series(area_dict)
print(area)

population_dict = {'CA':39250017, 'TX':27862596, 'NY':19745289, 'FL':20612439, 'IL':12801539} #人
population = pd.Series(population_dict)

states = pd.DataFrame({'population':population, 'area':area})
print(states)
print(states.index)
print(states.columns)

CA    423967
TX    695662
NY    141297
FL    170312
IL    149995
dtype: int64
    population    area
CA    39250017  423967
TX    27862596  695662
NY    19745289  141297
FL    20612439  170312
IL    12801539  149995
Index(['CA', 'TX', 'NY', 'FL', 'IL'], dtype='object')
Index(['population', 'area'], dtype='object')


In [8]:
print(states['area']['CA']) #先找欄位，再去找index
print(states['population']['IL'])

423967
12801539


In [9]:
#Ex2: DataFrame建構
import numpy as np
import pandas as pd

data = pd.DataFrame(np.random.rand(3,2),columns=['Fruit', 'Animal'],index=['KHH',"TPE",'HUA'])
print(data)

        Fruit    Animal
KHH  0.976502  0.664867
TPE  0.426285  0.466187
HUA  0.220661  0.847146


In [10]:
#Ex3: DataFrame建構

import numpy as np
import pandas as pd
A = np.zeros(3,dtype=[('colA','i8'), ('colB','f8'), ('colC','i8'), ('colD','i8')])
print(A)

data = pd.DataFrame(A)
print(data)

[(0, 0., 0, 0) (0, 0., 0, 0) (0, 0., 0, 0)]
   colA  colB  colC  colD
0     0   0.0     0     0
1     0   0.0     0     0
2     0   0.0     0     0


### Pandas Index物件使用

    1. Series和DataFrame物件，都需要包含一個顯示index(row的名稱)引用來做資料與數據的修改
    2. 如何建構一個有效的Pandas index
    3. 索引為不可以改變陣列

In [11]:
ind = pd.Index([2,3,5,7,11])
print(ind)
print(ind[1]) #indexing
print(ind[::2])

# inde[0] = 99 -->{ERROR}資料索引不可以改變
print("索引的長度:", ind.size)
print("索引的形狀", ind.shape)
print('索引ndim:', ind.ndim)
print("索引dtype:", ind.dtype)

Index([2, 3, 5, 7, 11], dtype='int64')
3
Index([2, 5, 11], dtype='int64')
索引的長度: 5
索引的形狀 (5,)
索引ndim: 1
索引dtype: int64


In [26]:
#Pandas物件用在跨資料集連接的操作

indA = pd.Index([1,2,3,4,5,7,9,])
indB = pd.Index([2,4,6,7,8,9,10])

print(indA & indB) # 兩個資料集的交集
print(indA | indB) # 兩個資料集的聯集
print(indA ^ indB) # 兩個資料集的對稱差集

Index([0, 0, 2, 4, 0, 1, 8], dtype='int64')
Index([3, 6, 7, 7, 13, 15, 11], dtype='int64')
Index([3, 6, 5, 3, 13, 14, 3], dtype='int64')


### 資料索引(Indexing)與選取(Selection)

In [15]:
#series資料選取: 與python dict (key-value)互相對應

import pandas as pd

data = pd.Series([60, 30, 40, 50, 100], index=['apple','banana','pear','mango','watermelon'])
print(data['banana'])
print(data['mango'])

if 'apple' in data:
    print("資料集中有apple這個水果")
else:
    print("沒有這個水果")

print(data.keys())
print(list(data.items()))

#可以做series資料的更改，但是不能做index更改
data['watermelon'] = 200
print(data)



30
50
資料集中有apple這個水果
Index(['apple', 'banana', 'pear', 'mango', 'watermelon'], dtype='object')
[('apple', 60), ('banana', 30), ('pear', 40), ('mango', 50), ('watermelon', 100)]
apple          60
banana         30
pear           40
mango          50
watermelon    200
dtype: int64


In [16]:
print(data['apple':'pear']) #界定需要的資料範圍
print("="*60)
print(data[0:3]) #用python slicing方式[start: stop but not include: step] *建議不要使用
print("="*60)
print(data[(data>30) & (data<100)]) #找出資料中數值>30且<100的資料

print(data[['mango','apple','pear']]) #指定看特定index的資料


apple     60
banana    30
pear      40
dtype: int64
apple     60
banana    30
pear      40
dtype: int64
apple    60
pear     40
mango    50
dtype: int64
mango    50
apple    60
pear     40
dtype: int64


In [17]:
import pandas as pd

data = pd.Series([60, 30, 40, 50, 100], index=['apple','banana','pear','mango','watermelon'])
print(data.loc['apple']) #data.loc:給欄位拿資料
print(data.iloc[0:2]) #data.iloc:給索引的門牌位置抓資料

60
apple     60
banana    30
dtype: int64


### DataFrame的資料選取

In [18]:
import pandas as pd

area_dict = {'CA':423967, 'TX':695662, 'NY':141297, 'FL':170312, 'IL':149995} #python dict
area = pd.Series(area_dict)

population_dict = {'CA':39250017, 'TX':27862596, 'NY':19745289, 'FL':20612439, 'IL':12801539} #人
population = pd.Series(population_dict)

data = pd.DataFrame({'area':area, 'popu':population})
print(data)

      area      popu
CA  423967  39250017
TX  695662  27862596
NY  141297  19745289
FL  170312  20612439
IL  149995  12801539


In [19]:
#取得某一個欄位的所有資料:
print(data.area)
print("="*60)

print(data['area'])
print("="*60)

#將欄位間運算結果成為另一個欄位資料
data['density'] = data['popu'] / data['area']
print(data)

CA    423967
TX    695662
NY    141297
FL    170312
IL    149995
Name: area, dtype: int64
CA    423967
TX    695662
NY    141297
FL    170312
IL    149995
Name: area, dtype: int64
      area      popu     density
CA  423967  39250017   92.578000
TX  695662  27862596   40.051916
NY  141297  19745289  139.743158
FL  170312  20612439  121.027520
IL  149995  12801539   85.346438


In [20]:
data.values #去除index與欄位名稱，將每一個索引的數值，結合成為陣列
print(data.values)
print(data.values[0])

[[4.23967000e+05 3.92500170e+07 9.25780002e+01]
 [6.95662000e+05 2.78625960e+07 4.00519160e+01]
 [1.41297000e+05 1.97452890e+07 1.39743158e+02]
 [1.70312000e+05 2.06124390e+07 1.21027520e+02]
 [1.49995000e+05 1.28015390e+07 8.53464382e+01]]
[4.23967000e+05 3.92500170e+07 9.25780002e+01]


In [21]:
data = data.T
print(data)

                   CA            TX            NY            FL            IL
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
popu     3.925002e+07  2.786260e+07  1.974529e+07  2.061244e+07  1.280154e+07
density  9.257800e+01  4.005192e+01  1.397432e+02  1.210275e+02  8.534644e+01


In [22]:
data = data.T
data = data['density']
print(data)
print(data.iloc[2])

CA     92.578000
TX     40.051916
NY    139.743158
FL    121.027520
IL     85.346438
Name: density, dtype: float64
139.74315802883288


In [33]:
#print(data['popu']['CA'])
#print(data.loc[data.popu>100, ['popu','density']])